[package]
name = "rcypher"
version = "0.1.0"
edition = "2024"

[dependencies]
aes = "0.8"
cbc = "0.1"
cipher = { version = "0.4", features = ["block-padding"] }
rustyline = "13.0"
rpassword = "7.3"
clap = { version = "4.4", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
bincode = "2.0.0-rc2"
chrono = "0.4"
anyhow = "1.0"
regex = "1.10"
tempfile = "3.23.0"
rand = "0.9.2"
num_enum = "0.7.5"
zeroize = "1.8.2"

[dev-dependencies]
assert_cmd = "2"
predicates = "3"

[profile.dev]
opt-level = 0
lto = "none"

[profile.release]
opt-level = 3
lto = "fat"
debug = "none"
strip = "symbols"
